@extends('templates.main')
@section('content')
    <div id="title-page" data-value="Authentication" data-value2="Account"></div>
    <div class="card">
        <div class="card-header fw-bold p-3 text-xss">Two Factor-Authentication</div>
        <div class="card-body">

            @if ($errors->all())
                <div class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <div>{{ $error }}</div>
                    @endforeach
                </div>
            @endif
            @if (session()->has('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @if (session()->has('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if (auth()->user()->google2fa == '1')
                <div class="alert alert-primary mb-4">
                    Two-Factor Authentication has been enabled. Each time you log in, you will need to enter the OTP
                    code generated by the Authenticator app. You can disable this by clicking the button below.
                </div>
                <div class="mb-0">
                    <a href="{{ url('account/disable-authentication') }}" class="btn btn-danger d-grid">Disable</a>
                </div>
            @else
                <form action="{{ url('account/proses-authentication') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-12">
                            <ol class="ps-3 mb-3">
                                <li class="fw-semibold">Install an authenticator app on your mobile device.</li>
                                <li class="fw-semibold mt-3">
                                    Scan the following QR code in your authenticator app.<br>
                                    <img src="{!! $render !!}" class="mt-2" width="150">
                                </li>
                                <li class="fw-semibold mt-3 ">
                                    Or configure your authenticator app manually using code:
                                    <div class="input-group" style="padding-right: 1rem !important;">
                                        <input type="text" name="secret" id="secret" class="form-control mt-2"
                                            value="{{ $secret }}" readonly>
                                        <button type="button" data-clipboard-text="{{ $secret }}"
                                            class="btn copy btn-primary btn-sm mt-2">Copy</button>
                                    </div>
                                </li>
                                <li class="fw-semibold mt-3">
                                    Enter the code from your authenticator app below:
                                    <div style="padding-right: 1rem !important;">
                                        <input type="number" class="form-control mt-2" name="token" autocomplete="off">
                                    </div>
                                </li>
                                <li class="fw-semibold mt-3">
                                    Enter your password:
                                    <div style="padding-right: 1rem !important;">
                                        <input type="password" class="form-control mt-2" name="password">
                                    </div>
                                </li>
                            </ol>
                        </div>
                        <div class="col-12 d-grid">
                            <button type="submit" class="btn btn-primary mt-3">Enable</button>
                        </div>
                    </div>
                </form>
            @endif
        </div>
    </div>
@endsection
